//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLP2D.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VLP2D.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средне-арифметическая.
        /// </summary>
        public static string strArithMean {
            get {
                return ResourceManager.GetString("strArithMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бисопряженных градиентов.
        /// </summary>
        public static string strBiconjGrad {
            get {
                return ResourceManager.GetString("strBiconjGrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должны быть заданы либо &apos;funcLeft&apos;, &apos;funcRight&apos;, &apos;funcTop&apos;, &apos;funcBottom&apos; либо &apos;funcBoundary&quot;..
        /// </summary>
        public static string strBoundaryParameters {
            get {
                return ResourceManager.GetString("strBoundaryParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время счета:.
        /// </summary>
        public static string strCalcTime {
            get {
                return ResourceManager.GetString("strCalcTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посчитать.
        /// </summary>
        public static string strCalculate {
            get {
                return ResourceManager.GetString("strCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3-слойная Чебышевская.
        /// </summary>
        public static string strChebish3 {
            get {
                return ResourceManager.GetString("strChebish3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чебышевское ускорение.
        /// </summary>
        public static string strChebishBoost {
            get {
                return ResourceManager.GetString("strChebishBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сравнение с аналитическим.
        /// </summary>
        public static string strCompareAnalytic {
            get {
                return ResourceManager.GetString("strCompareAnalytic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сопряженных градиентов.
        /// </summary>
        public static string strConjGrad {
            get {
                return ResourceManager.GetString("strConjGrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Циклической редукции (CR).
        /// </summary>
        public static string strCR {
            get {
                return ResourceManager.GetString("strCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка вычисления выражения.
        /// </summary>
        public static string strExpressionError {
            get {
                return ResourceManager.GetString("strExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разделения переменных (FA).
        /// </summary>
        public static string strFA {
            get {
                return ResourceManager.GetString("strFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неполной редукции (FACR(1)).
        /// </summary>
        public static string strFACR {
            get {
                return ResourceManager.GetString("strFACR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Быстрый индекс.
        /// </summary>
        public static string strFastIndex {
            get {
                return ResourceManager.GetString("strFastIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Быстрое преобразование Фурье.
        /// </summary>
        public static string strFFT {
            get {
                return ResourceManager.GetString("strFFT", resourceCulture);
            }
        }

		/// <summary>
		///   Ищет локализованную строку, похожую на strReduction.
		/// </summary>
		public static string strReduction
		{
			get
			{
				return ResourceManager.GetString("strReduction", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на Файл {0}.
		/// </summary>
		public static string strFile {
            get {
                return ResourceManager.GetString("strFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество значений должно быть 4..
        /// </summary>
        public static string strFour {
            get {
                return ResourceManager.GetString("strFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорейшего спуска.
        /// </summary>
        public static string strGradDesc {
            get {
                return ResourceManager.GetString("strGradDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индекс:.
        /// </summary>
        public static string strIndex {
            get {
                return ResourceManager.GetString("strIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициализация:.
        /// </summary>
        public static string strInitialization {
            get {
                return ResourceManager.GetString("strInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интерполяция.
        /// </summary>
        public static string strInterpol {
            get {
                return ResourceManager.GetString("strInterpol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итераций:.
        /// </summary>
        public static string strIterations {
            get {
                return ResourceManager.GetString("strIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жорданово ускорение.
        /// </summary>
        public static string strJordanBoost {
            get {
                return ResourceManager.GetString("strJordanBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр L.
        /// </summary>
        public static string strLParameter {
            get {
                return ResourceManager.GetString("strLParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маршевый векторный.
        /// </summary>
        public static string strMarchingVector {
            get {
                return ResourceManager.GetString("strMarchingVector", resourceCulture);
            }
        }

		/// <summary>
		///   Ищет локализованную строку, похожую на Маршевый скалярный.
		/// </summary>
		public static string strMarchingScalar
		{
			get
			{
				return ResourceManager.GetString("strMarchingScalar", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на Матричной прогонки.
		/// </summary>
		public static string strMatrProgonka {
            get {
                return ResourceManager.GetString("strMatrProgonka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднее (min+max)/2.
        /// </summary>
        public static string strMean {
            get {
                return ResourceManager.GetString("strMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод/Схема.
        /// </summary>
        public static string strMethodOrScheme {
            get {
                return ResourceManager.GetString("strMethodOrScheme", resourceCulture);
            }
        }

		/// <summary>
		///   Ищет локализованную строку, похожую на strIterationsCount.
		/// </summary>
		public static string strIterationsCount
		{
			get
			{
				return ResourceManager.GetString("strIterationsCount", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на strHeatMapsCount.
		/// </summary>
		public static string strHeatMapsCount
		{
			get
			{
				return ResourceManager.GetString("strHeatMapsCount", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на strStepViz.
		/// </summary>
		public static string strStepViz
		{
			get
			{
				return ResourceManager.GetString("strStepViz", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на Отклонение.
		/// </summary>
		public static string strDeviation
		{
            get {
                return ResourceManager.GetString("strDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальных невязок.
        /// </summary>
        public static string strMinRes {
            get {
                return ResourceManager.GetString("strMinRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Многосеточный (V-цикл).
        /// </summary>
        public static string strMultiGridVC {
            get {
                return ResourceManager.GetString("strMultiGridVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Многопоточность.
        /// </summary>
        public static string strMultithreading {
            get {
                return ResourceManager.GetString("strMultithreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствуют(или неверные) данные в папке {0}.
        /// </summary>
        public static string strNoInputData {
            get {
                return ResourceManager.GetString("strNoInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения параметра {0}={1}.
        /// </summary>
        public static string strParsingParameterError {
            get {
                return ResourceManager.GetString("strParsingParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кусочно-линейная(Средне-арифметическая).
        /// </summary>
        public static string strPiecewise {
            get {
                return ResourceManager.GetString("strPiecewise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кусочно-линейная(Весовая).
        /// </summary>
        public static string strPiecewiseWeight {
            get {
                return ResourceManager.GetString("strPiecewiseWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогонка.
        /// </summary>
        public static string strProgonka {
            get {
                return ResourceManager.GetString("strProgonka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попеременно-треугольный.
        /// </summary>
        public static string strPTM {
            get {
                return ResourceManager.GetString("strPTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение входных данных.
        /// </summary>
        public static string strReadInputData {
            get {
                return ResourceManager.GetString("strReadInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует обязательный параметр &apos;{0}&apos;.
        /// </summary>
        public static string strReqParameterMissed {
            get {
                return ResourceManager.GetString("strReqParameterMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты.
        /// </summary>
        public static string strResults {
            get {
                return ResourceManager.GetString("strResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить анимир. GIF.
        /// </summary>
        public static string strSavingGIF {
            get {
                return ResourceManager.GetString("strSavingGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Простой итерации.
        /// </summary>
        public static string strSimpleIteration {
            get {
                return ResourceManager.GetString("strSimpleIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скользящей итерации.
        /// </summary>
        public static string strSlidingIteration {
            get {
                return ResourceManager.GetString("strSlidingIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верхней релаксации.
        /// </summary>
        public static string strSOR {
            get {
                return ResourceManager.GetString("strSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расщепления.
        /// </summary>
        public static string strSplitting {
            get {
                return ResourceManager.GetString("strSplitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стабилизированный.
        /// </summary>
        public static string strStabilized {
            get {
                return ResourceManager.GetString("strStabilized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задача.
        /// </summary>
        public static string strTask {
            get {
                return ResourceManager.GetString("strTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переменных направлений.
        /// </summary>
        public static string strVarDir {
            get {
                return ResourceManager.GetString("strVarDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Визуализация.
        /// </summary>
        public static string strVisualization {
            get {
                return ResourceManager.GetString("strVisualization", resourceCulture);
            }
        }
		/// <summary>
		///   Ищет локализованную строку, похожую на Half.
		/// </summary>
		public static string strPrecisionHalf
		{
			get
			{
				return ResourceManager.GetString("strPrecisionHalf", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на Float.
		/// </summary>
		public static string strPrecisionFloat
		{
			get
			{
				return ResourceManager.GetString("strPrecisionFloat", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на Double.
		/// </summary>
		public static string strPrecisionDouble
		{
			get
			{
				return ResourceManager.GetString("strPrecisionDouble", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на DD128.
		/// </summary>
		public static string strPrecisionDD128
		{
			get
			{
				return ResourceManager.GetString("strPrecisionDD128", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на QD256.
		/// </summary>
		public static string strPrecisionQD256
		{
			get
			{
				return ResourceManager.GetString("strPrecisionQD256", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на strCalculating.
		/// </summary>
		public static string strCalculating
		{
			get
			{
				return ResourceManager.GetString("strCalculating", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на strComparing.
		/// </summary>
		public static string strComparing
		{
			get
			{
				return ResourceManager.GetString("strComparing", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на strMethod.
		/// </summary>
		public static string strMethod
		{
			get
			{
				return ResourceManager.GetString("strMethod", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на strMethodSN.
		/// </summary>
		public static string strMethodSN
		{
			get
			{
				return ResourceManager.GetString("strMethodSN", resourceCulture);
			}
		}

		/// <summary>
		///   Ищет локализованную строку, похожую на strMethodBM.
		/// </summary>
		public static string strMethodBM
		{
			get
			{
				return ResourceManager.GetString("strMethodBM", resourceCulture);
			}
		}
	}
}
